default:
  Destination_MessageQueueServer_Address: 192.168.1.41
  Destination_MessageQueueServer_PortNum: 61616
  Type_Message_Queue_Type: activeMQ # Possible Types Supported: activeMQ, rabbitMQ
  Incoming_Request_Queue_Name: AnomRequestQ_Test
  Outcoming_Request_Queue_Name: AnomResponseQ_Test
  Outcoming_Error_Queue_Name: AnomErrorQ
  Retry_Request_Queue_Name: AnomRetryQ
  Breathing_Time_Seconds_4_NextRequest: 1
  Incoming_Request_Retry_count: 10